-- Table: public.Empresas

-- DROP TABLE IF EXISTS public."Empresas";

CREATE TABLE IF NOT EXISTS public."Empresas"
(
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nome" character varying(200) COLLATE pg_catalog."default" NOT NULL,
    "Cnpj" character varying(14) COLLATE pg_catalog."default" NOT NULL,
    "FaturamentoMensal" numeric(18,2) NOT NULL,
    "Ramo" integer NOT NULL,
    "IsDeleted" boolean NOT NULL,
    CONSTRAINT "PK_Empresas" PRIMARY KEY ("Id")
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public."Empresas"
    OWNER to postgres;
-- Index: IX_Empresas_Cnpj

-- DROP INDEX IF EXISTS public."IX_Empresas_Cnpj";

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Empresas_Cnpj"
    ON public."Empresas" USING btree
    ("Cnpj" COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;